version: '3'

services:
  postgres:
    image: postgres
  app:
    build: .
    command: python proj/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
